-- Legacy schema: the tables Hibernate (ddl-auto=update) created before Flyway was introduced,
-- exactly as they stood before V1 - i.e. WITHOUT the columns later migrations add to them
-- (audit timestamps in V12, minor-units money in V13, fulfillment in V11, coupons in V16), and
-- WITH the old double-precision money columns V13 converts from.
--
-- Why version 0: existing databases were baselined at version 0
-- (spring.flyway.baseline-version=0), so Flyway treats this migration as "below baseline" and
-- never runs it there - their legacy tables already exist. A brand-new, empty database has no
-- baseline, so Flyway runs V0 first and every later migration applies on top of it. That makes
-- the schema fully reproducible from migrations, and lets dev run ddl-auto=validate like prod.
--
-- Generated from pg_dump of a live dev database, then rewound by hand to the pre-V1 state.

CREATE TABLE users (
    user_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    email      VARCHAR(50)  NOT NULL,
    enabled    BOOLEAN      NOT NULL,
    name       VARCHAR(255),
    password   VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    username   VARCHAR(20)  NOT NULL,
    CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email),
    CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username)
);

CREATE TABLE roles (
    role_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(20),
    CONSTRAINT roles_role_name_check CHECK (role_name IN ('ROLE_USER', 'ROLE_SELLER', 'ROLE_ADMIN'))
);

CREATE TABLE user_role (
    user_id BIGINT  NOT NULL REFERENCES users (user_id),
    role_id INTEGER NOT NULL REFERENCES roles (role_id),
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE oauth_accounts (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    linked_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    provider         VARCHAR(50)  NOT NULL,
    provider_user_id VARCHAR(255) NOT NULL,
    user_id          BIGINT       NOT NULL REFERENCES users (user_id),
    CONSTRAINT ukqattdvs18omb33um7ge1tb5ex UNIQUE (provider, provider_user_id)
);

CREATE TABLE refresh_token (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    family_id  UUID         NOT NULL,
    revoked    BOOLEAN      NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    user_id    BIGINT       NOT NULL REFERENCES users (user_id)
);

CREATE TABLE password_reset_tokens (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expiration_date TIMESTAMP(6) NOT NULL,
    token           VARCHAR(255) NOT NULL,
    used            BOOLEAN      NOT NULL,
    user_id         BIGINT       NOT NULL REFERENCES users (user_id),
    CONSTRAINT uk71lqwbwtklmljk3qlsugr1mig UNIQUE (token),
    CONSTRAINT ukla2ts67g4oh2sreayswhox1i6 UNIQUE (user_id)
);

CREATE TABLE verification_token (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expiry_date TIMESTAMP(6),
    token       VARCHAR(255) NOT NULL,
    user_id     BIGINT       NOT NULL REFERENCES users (user_id),
    CONSTRAINT ukp678btf3r9yu6u8aevyb4ff0m UNIQUE (token),
    CONSTRAINT ukq6jibbenp7o9v6tq178xg88hg UNIQUE (user_id)
);

CREATE TABLE addresses (
    address_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building_name VARCHAR(255) NOT NULL,
    city          VARCHAR(255) NOT NULL,
    country       VARCHAR(255) NOT NULL,
    pincode       VARCHAR(255) NOT NULL,
    state         VARCHAR(255) NOT NULL,
    street        VARCHAR(50)  NOT NULL,
    user_id       BIGINT       NOT NULL REFERENCES users (user_id)
);

CREATE TABLE categories (
    category_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(255) NOT NULL
);

CREATE TABLE products (
    product_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description   VARCHAR(255),
    discount      DOUBLE PRECISION NOT NULL,
    image         VARCHAR(255),
    product_name  VARCHAR(255),
    quantity      INTEGER,
    price         DOUBLE PRECISION,
    special_price DOUBLE PRECISION,
    category_id   BIGINT REFERENCES categories (category_id),
    seller_id     BIGINT REFERENCES users (user_id)
);

CREATE TABLE carts (
    cart_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total_price DOUBLE PRECISION,
    user_id     BIGINT REFERENCES users (user_id),
    CONSTRAINT uk64t7ox312pqal3p7fg9o503c2 UNIQUE (user_id)
);

CREATE TABLE cart_items (
    cart_item_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discount      DOUBLE PRECISION NOT NULL,
    product_price DOUBLE PRECISION,
    quantity      INTEGER,
    cart_id       BIGINT REFERENCES carts (cart_id),
    product_id    BIGINT REFERENCES products (product_id)
);

-- Legacy, unused by current code (superseded by payment_attempts) but still mapped by
-- order.Payment, so the table must exist.
CREATE TABLE payments (
    payment_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_method      VARCHAR(255),
    pg_name             VARCHAR(255),
    pg_payment_id       VARCHAR(255),
    pg_response_message VARCHAR(255),
    pg_status           VARCHAR(255)
);

CREATE TABLE orders (
    order_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email        VARCHAR(255) NOT NULL,
    order_date   DATE,
    order_status VARCHAR(255),
    total_amount DOUBLE PRECISION,
    address_id   BIGINT REFERENCES addresses (address_id),
    payment_id   BIGINT REFERENCES payments (payment_id),
    CONSTRAINT ukhaujdjk1ohmeixjhnhslchrp1 UNIQUE (payment_id)
);

CREATE TABLE order_items (
    order_item_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discount              DOUBLE PRECISION,
    ordered_product_price DOUBLE PRECISION,
    price                 DOUBLE PRECISION,
    quantity              INTEGER,
    order_id              BIGINT REFERENCES orders (order_id),
    product_id            BIGINT REFERENCES products (product_id)
);

CREATE TABLE email_logs (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          TIMESTAMP(6),
    email_type          VARCHAR(255),
    error_message       TEXT,
    metadata_json       TEXT,
    provider_message_id VARCHAR(255),
    provider_used       VARCHAR(255),
    recipient           VARCHAR(255),
    retrycount          INTEGER NOT NULL,
    sent_at             TIMESTAMP(6),
    status              VARCHAR(255),
    CONSTRAINT email_logs_status_check CHECK (status IN ('QUEURED', 'SENT', 'FAILED', 'BOUNCED', 'RETRYING'))
);
