ALTER TABLE reviews ADD COLUMN seller_reply VARCHAR(2000);
ALTER TABLE reviews ADD COLUMN seller_replied_at TIMESTAMP;
ALTER TABLE reviews ADD COLUMN hidden BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE reviews ADD COLUMN hidden_reason VARCHAR(500);
